x86, kvmtool: Fix build when KVM_TOOL_TEST_ENABLE is set
Commit ab7db91705e9 ("virtio-net: auto-tune mergeable rx buffer size for
improved performance") requires CONFIG_AVERAGE to be set, which is
selected by CONFIG_VIRTIO_NET, otherwise the build fails:

drivers/built-in.o: In function `virtnet_poll':
virtio_net.c:(.text+0x11d51f): undefined reference to `ewma_add'
drivers/built-in.o: In function `virtnet_probe':
virtio_net.c:(.text+0x11e668): undefined reference to `ewma_init'

CONFIG_KVM_TOOL_TEST_ENABLE selects CONFIG_VIRTIO_NET but not
CONFIG_AVERAGE so the build breaks when enabling it.

Select CONFIG_AVERAGE for CONFIG_KVMTOOL_TEST_ENABLE.

Signed-off-by: David Rientjes <rientjes@google.com>
Signed-off-by: Pekka Enberg <penberg@kernel.org>